services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: kaggle-bank-fraud:latest
    volumes:
      - ./data:/app/data
      - ./data:/input

      - ./models:/app/models
      - ./models:/input/models

      - ./submissions:/app/submissions
      - ./submissions:/output
    restart: "no"
